pyproject.toml
Update websockets dependency to latest version.
This will make realtime-py compatible with other libraries using websockets.
Related: #35
=> build: update websockets version

pyproject.toml, realtime/channel.py, realtime/connection.py, realtime/message.py, realtime/types.py
The goal of this PR is to make the code more standard and compatible with lower versions of Python as well
Maybe there are some things to consider like:
1. Include `typing-extensions` to the dependencies (If is not in the dependencies)
2. Use the `typing` versions of `list` and `dict` (I changed those in this PR)
=> ♻️ Standardize types and improve consistency

docs/realtime/channel.html, realtime/channel.py
Very minor thing - there were a few occurrences of `set_chanel` when it should be `set_channel` in the docs and in a docstring.
=> fix spelling mistake: set_chanel->set_channel

poetry.lock, pyproject.toml
This PR removes the `dataclasses` dependency, which is not needed as the library is currently targeting Python 3.7+ (according to the `pyproject.toml`). From Python 3.7 onwards `dataclasses` is a part of Python standard library (https://docs.python.org/3/whatsnew/3.7.html).
Current behaviour (`dataclasses` being a declared dependency) leads to bugs and crashes when using more modern versions of Python, as discussed in the following issue: https://github.com/supabase-community/realtime-py/issues/22
Closes #22
=> Remove `dataclasses` dependency

realtime/connection.py
Bug fix that corrects the type argument provided to the `cast` method during `Socket` initialisation
Documented in #58 
Correctly initialises the `Socket` class
NA
=> fix: correct type argument for cast method during socket initialisation

realtime/connection.py
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
=> fix: use shared types

realtime/connection.py
fixes: https://github.com/supabase-community/realtime-py/issues/87
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
=> fix: Remove the global logger call from realtime-py

poetry.lock, pyproject.toml
`asyncio` as a standalone library hasn't been relevant in a loooong time, as it is in the standard library. This PR removes the old reference implementation.
=> chore: remove reference asyncio library

realtime/_async/channel.py, realtime/_async/client.py
Bug fix
Auto reconnect is broken, because a non-existing method is called (`_connect`)
Call the correct method (`connect`)
=> fix: update broken method calls

realtime/_async/channel.py
Fix https://github.com/supabase/supabase-py/issues/932
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
=> fix: add missing arg on on_join_push_timeout

realtime/_async/client.py, realtime/_sync/client.py
- Fix types to use `Option[T]` instead of Unions of Nones.
=> fix: Types to use Option[T]

realtime/_async/client.py, tests/test_connection.py
- Do not send expired token.
- Fix #243
- Based but not copied from: https://github.com/supabase/realtime-js/pull/437/files#diff-f5a6b192eb9d6c05f61c33d8629b814ad893fbfb729bfa7af9b226e5c87d2e85R343-R350
=> fix: prevent sending expired tokens

realtime/_async/channel.py, realtime/_async/client.py, realtime/_async/push.py, realtime/_sync/channel.py, realtime/_sync/client.py
Fix default mutable arguments originally fixed by: https://github.com/supabase/realtime-py/pull/204
=> fix: default mutable arguments

.github/workflows/ci.yml, Makefile, pyproject.toml, realtime/_async/channel.py, realtime/_async/client.py, tests/test_connection.py
Close https://github.com/supabase/realtime-py/issues/200
Close https://github.com/supabase/realtime-py/issues/259
This PR adds support for `system` event, but also fixes failing CI runs
=> feat: add support for  `system` event

realtime/_async/client.py
I think it should fix #258 
When `auto_reconnect` is `True`, the channel is attempted to joined but it uses defaul payload which is empty. Instead it should use the existing payload that was originally used when the channel was first joined.
=> fix: send correct payload to channel on reconnect

realtime/_async/client.py, realtime/types.py, tests/test_connection.py
- Sets default heartbeat interval to 25s
- Adds a new test for asserting initialization of client.
=> fix: Set default heartbeat interval to 25s

realtime/_async/client.py, tests/test_connection.py
Fix https://github.com/supabase/realtime-py/issues/289
- Make sure to cleanup current `heartbeat` and `listen` tasks before creating a new one.
- Add tests for verifying multiple connect behavior.
=> fix: cleanup current heartbeat and listen tasks before creating a new one

README.md
docs update
The example in the README doesn't work.
The example in the README is now a working example.
=> chore(docs): update example in readme

tests/test_timer.py
Adds tests for async timer to get coverage over 80%
=> Test async timer

realtime/_async/client.py, realtime/exceptions.py
Fix #331 by catching only `websockets.exceptions.ConnectionClosedError` inside `_listen`, `send` and `_heartbeat`, re-raising any other errors that are raised from these calls.
Errors thrown from calling any of the callbacks are not shown to the user due to `_listen` suppressing them. The user is only able to see it if they have `logging` set
Any error not related to the websocket connection is ignored and subsequently shown to the user.
`send` and  `_heartbeat` can only ever raise `ConnectionClosedError`, so this should effectively be a no-op for those, however, `_listen` may raise any arbitrary exception, given that it calls callbacks. Still, `_listen` is spawned as a background thread, which means that any errors raised from it will not immediately be raised to the user; instead, …
=> fix: Do not supress callback exceptions

realtime/_async/channel.py, realtime/_async/client.py, realtime/_async/presence.py, realtime/_async/push.py, realtime/message.py, realtime/types.py, tests/test_connection.py, tests/test_presence.py
Validate messages according to realtime protocol specification.
The server receives an opaque `Message` object inside the main `_listen` loop that is then parsed inside the `AsyncRealtimeChannel._trigger` function, which also is responsible for dispatching callbacks. 
The same `_trigger` logic is also responsible for calling the callbacks for message acknowledgments, registered by `AsyncPush.receive`, by creating virtual events depending on the `AsyncPush` refs. This makes the function logic very hard to understand, and mixes multiple different use cases in the same callbacks.
First, introduce `ServerMessage` type that represent all possible messages that the server might send to a client, and use `pydantic`'s `TypeAdapter` to automatically parse and validate the payload types. 
Then, …
=> feat: validate server message
